version: "3.8"

services:
  frontend:
    build:
      context: ../frontend  # Reference to the frontend folder
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .  # Reference to the backend folder where docker-compose.yml is located
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://db:27017/mernstack
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
